### ISSUE TITLE
Function limiter_value not defined

### ISSUE THREAD

**Issue by angelenriquecano** [jimmonen11/electrolyzer-module#1]
Hi, 
Thanks for shring this model.
Trying to execute it, I got error in Flux_Limiter at line 39, the function `limiter_value` is not defined.
Best regards, Angel

**Comment by jimmonen11** [comment]
Thanks for pointing this out. I had just done this all locally on my PC and uploaded to GitHub, but missed a file. limiter_value.m is now provided.
Let me know if you run into other problems!
